"""Prepare unsigned Base Sepolia contracts from the reviewed public verifier key.

No network, .env, wallet, existing secret, signature, payment or deployment.
The original setup remains untouched. Output must be a new .build directory.
"""
import argparse
import json
from pathlib import Path
import subprocess
import tempfile
from age_artifacts import ROOT, BASE, checked_public_setup, digest_file

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--out', default='.build/age-deployment')
args = parser.parse_args()
destination = (ROOT / args.out).resolve()
assert destination.is_relative_to((ROOT / '.build').resolve()) and destination != (ROOT / '.build').resolve()
assert not destination.exists(), 'Use a new output directory; never overwrite a reviewed package'
pins = checked_public_setup()
destination.parent.mkdir(parents=True, exist_ok=True)
with tempfile.TemporaryDirectory(prefix='age-deployment-', dir=ROOT / '.build') as folder:
    stage = Path(folder)
    # Export from the pinned pkv instead of trusting a cached Verifier.sol.
    # patch-age-verifier.py verifies the complete upstream template hash.
    subprocess.run(['python3', str(ROOT / 'scripts/patch-age-verifier.py'),
                    str(BASE / 'provekit/provekit/groth16/contracts/ProvekitGroth16Verifier.sol'),
                    str(stage / 'template.sol')], check=True)
    subprocess.run([str(BASE / 'target/release/provekit-cli'), 'export-solidity',
                    '--pkv', str(BASE / 'artifacts/age.pkv'), '--template', str(stage / 'template.sol'),
                    '--out', str(stage / 'Verifier.sol')], check=True)
    sources = {'Verifier.sol': {'content': (stage / 'Verifier.sol').read_text()},
               'MateAgeGate.sol': {'content': (ROOT / 'contracts/src/MateAgeGate.sol').read_text()}}
    result = subprocess.run(['node', str(ROOT / 'scripts/compile-age-deployment.mjs')],
                            input=json.dumps(sources), text=True, capture_output=True, check=True)
    package = json.loads(result.stdout)
    package.update(format=1, chainId=84532, testnetOnly=True, deployed=False, publicSetup=pins,
                   sourceSHA256={name: digest_file(stage / name) if name == 'Verifier.sol'
                                 else digest_file(ROOT / 'contracts/src' / name) for name in sources},
                   limitations=['single-party experimental setup', 'revocation is not checked',
                                'physical card and live testnet acceptance remain required'])
    (stage / 'deployment.json').write_text(json.dumps(package, indent=2) + '\n')
    artifact_pins = json.loads((ROOT / 'config/age-deployment-pins.json').read_text())
    assert artifact_pins['format'] == 1
    assert digest_file(stage / 'deployment.json') == artifact_pins['deploymentSHA256'], \
        'Generated bytecode differs from the independently reviewed build; review before changing its pin'
    (stage / 'MateAgeGate.sol').write_text(sources['MateAgeGate.sol']['content'])
    (stage / 'README.txt').write_text('Unsigned PUBLIC Base Sepolia deployment package. No deployment performed.\n'
        'Deploy ProvekitGroth16Verifier first; its runtime must match verifier.runtimeCodeHash.\n'
        'MateAgeGate requires that verifier address and exact runtime code hash as constructor arguments.\n'
        'Use only after explicit authorization of the testnet deployer and gas budget.\n'
        'No synthetic-root gate or test token is included. No key, PIN, certificate or witness is included.\n')
    stage.rename(destination)
print('Prepared unsigned public age contracts at ' + str(destination.relative_to(ROOT)))
